In [7]:
from requests import get,post,put,delete
import json
import pandas as pd
from IPython.display import display, HTML

In [8]:
# url = 'https://dsbox02.isi.edu:8888/fs'
url = 'http://localhost:6733'
search_url = '/similarity/faiss/nn'
sentence_url = '/similarity/faiss/nn/sentence'

In [9]:
qnode = 'Q2452129'
r = get(f'{url}/{search_url}/{qnode}')
df = pd.DataFrame(r.json())

df

,sim,qnode1,qnode1_label,qnode2,qnode2_label
0,148.569199,Q2452129,'Bartolomeo d\'Alviano',Q24707765,'Giovanni Maccari'
1,171.556885,Q2452129,'Bartolomeo d\'Alviano',Q24578841,'Luciano Alberici'
2,172.356262,Q2452129,'Bartolomeo d\'Alviano',Q24577129,'Giovanni Caracciolo di Vietri'
3,176.069458,Q2452129,'Bartolomeo d\'Alviano',Q2461472,'Pandulf IV of Capua'
4,178.397308,Q2452129,'Bartolomeo d\'Alviano',Q1032942,'Nolfo da Montefeltro'
5,190.904572,Q2452129,'Bartolomeo d\'Alviano',Q24701506,'Armando Varricchio'

In [10]:
# get more results back, change k
r = get(f'{url}/{search_url}/{qnode}?k=17&debug=true')
df = pd.DataFrame(r.json())
display(HTML(df.fillna('').to_html(index=False)))

In [11]:
# debug=true, get sentences back
qnode = 'Q2452129'
r = get(f'{url}/{search_url}/{qnode}?k=10&debug=true')
df = pd.DataFrame(r.json())
display(HTML(df.fillna('').to_html(index=False)))

In [12]:
sentence = 'multicooker, automated cooking appliance is Multicookers, culinary equipment, home appliance, pressure cooker.'
r = get(f'{url}/{sentence_url}/{sentence}?k=20&debug=true')
df = pd.DataFrame(r.json())

df

,sim,input_sentence,qnode,qnode_label,qnode_sentence
0,450.720734,"multicooker, automated cooking appliance is Mu...",Q2458198,'Chushkopek',"Chushkopek, household appliance.\n"
1,458.899261,"multicooker, automated cooking appliance is Mu...",Q1039303,'cooking method',"cooking method, method to prepare a dish is me..."
2,465.813110,"multicooker, automated cooking appliance is Mu...",Q1034869,'cappelletti',"cappelletti, type of pasta is Cappelletti, pas..."
3,494.419678,"multicooker, automated cooking appliance is Mu...",Q24621311,'Borde stoves',"Borde stoves is Borde stoves, device.\n"
4,499.697998,"multicooker, automated cooking appliance is Mu...",Q2467917,'molecular propeller',"molecular propeller, class of chemical compoun..."
5,502.747314,"multicooker, automated cooking appliance is Mu...",Q24719668,'Ergonomics of household appliance assembly',"Ergonomics of household appliance assembly, co..."
6,526.504578,"multicooker, automated cooking appliance is Mu...",Q10373415,'Sopa de lacassá',"Sopa de lacassá, Macanese soup is soup.\n"
7,543.207520,"multicooker, automated cooking appliance is Mu...",Q24711750,,"It is dish, pastry.\n"
8,554.087524,"multicooker, automated cooking appliance is Mu...",Q103065377,'Can Grill',"Can Grill, masia in Sant Pere de Vilamajor (Ca..."
9,558.722168,"multicooker, automated cooking appliance is Mu...",Q2461918,'Pamonha',"Pamonha, traditional Brazilian food is Pamonha..."
10,559.808899,"multicooker, automated cooking appliance is Mu...",Q2453280,"'De Hoop, Bunschoten'","De Hoop, Bunschoten is De Hoop, Bunschoten, gr..."
11,560.854492,"multicooker, automated cooking appliance is Mu...",Q2460568,'turbine generator set',"turbine generator set, compound set of steam o..."
12,564.314331,"multicooker, automated cooking appliance is Mu...",Q24739544,'Llibre d\'aparellar de menjar',Llibre d\'aparellar de menjar is cookbook.\n
13,566.867065,"multicooker, automated cooking appliance is Mu...",Q10379618,'buckwheat kasha',"buckwheat kasha, type of porridge is Buckwheat..."
14,574.765320,"multicooker, automated cooking appliance is Mu...",Q24574381,'clathrin-coated pit assembly',"clathrin-coated pit assembly, The aggregation,..."
15,582.032288,"multicooker, automated cooking appliance is Mu...",Q10374398,'stuffat tal-qarnit',"stuffat tal-qarnit, Maltese octopus stew is st..."
16,584.345337,"multicooker, automated cooking appliance is Mu...",Q1031787,'gözleme',"gözleme, Turkish cuisine dish is Gözleme, food..."
17,584.465942,"multicooker, automated cooking appliance is Mu...",Q247225,'Dekatron',"Dekatron, electrical component is Dekatrons, c..."
18,589.574219,"multicooker, automated cooking appliance is Mu...",Q2459593,"'De Hoop, Wemeldinge'","De Hoop, Wemeldinge is De Hoop, Wemeldinge, gr..."
19,595.271729,"multicooker, automated cooking appliance is Mu...",Q2472574,'tea strainer',"tea strainer, type of strainer is Strainers.\n"
20,595.680542,"multicooker, automated cooking appliance is Mu...",Q2474403,'Maqluba',"Maqluba, food is Maqluba, rice dish.\n"